### ISSUE TITLE
What happened to the revision history for this repository?

### ISSUE THREAD

**Issue by anderbubble** [IBMSpectrumComputing/lsf-drmaa#1]
lsf-drmaa did not start development just 6 days ago; so what happened to all the revision history?

edit: we are an IBM / Platform/LSF customer using lsf-drmaa

**Comment by liuboxa** [comment]
I apologize, this is caused by my mistake, a wrong git command and it can not recover. sorry.

**Comment by anderbubble** [comment]
We happen to have a clone in bitbucket with the last Platform commit being b7ef66c5513810c445251bee41d8e1ebb1e3d323 (2014-07-10). We'd prefer that you maintain as much history as possible. Could we help you restore at least the history that we have?

**Comment by liuboxa** [comment]
sure, that's great, thanks very much.

**Comment by anderbubble** [comment]
Cool. What's the best way for us to get the history to you? Do we need to send you a pull request? Do you give us write access to the repo?

Ideally, your mater branch would reincorporate the history that we have, and and missing history between what we have and any commits you have in the repo right now would be rebased on top of that. How does that sound?

**Comment by adamsla** [comment]
If you can please create a pull request that would be great.  I for one would also like to have the history as well.

**Comment by wanggxa** [comment]
@anderbubble, we have to close this request since there is no response from you for a long time. Feel free to open if you would like to contribute. Thanks!
