### ISSUE TITLE
How to specify queue?

### ISSUE THREAD

**Issue by kretch** [IBMSpectrumComputing/lsf-drmaa#10]
Hi there.
I'm trying to build DRMAA in our corporate environment, where there are multiple clusters and queues.
How does one specify the queue for running a specific job?

**Comment by adamsla** [comment]
If you follow the documentation here: http://ibmspectrumcomputing.github.io/lsf-drmaa/, you can use space delimited LSF options in the native specification.  Search for "Native Specification" in the link and read how this is accomplished.

**Comment by adamsla** [comment]
If you find that response sufficient, simply close this issue.
