### ISSUE TITLE
configure  --with-lsf-static failed in LSF 10.1.0.6

### ISSUE THREAD

**Issue by chenja2000** [IBMSpectrumComputing/lsf-drmaa#13]
confiure in both  lsf-drmaa-1.11.tar.gz and  lsf-drmaa-2189cde7ecd083ccbd53ae244fbd9ccd8c533a16.zip failed  in LSF 10.1.0.6.

# ./configure --with-lsf-static
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
...
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
configure: checking for LSF
checking for LSF compile flags... -I/scratch/support/jamesc1/lsf/101/10.1/include
checking for LSF library dir... /scratch/support/jamesc1/lsf/101/10.1/linux2.6-glibc2.3-x86_64/lib
checking for main in -ldl... yes
checking for main in -lnsl... yes
checking for main in -lm... yes
checking for main in -lrt... yes
checking for usable LSF libraries/headers... *** The LSF test program failed to link or run. See the file config.log
*** for the exact error that occured.
no
configure: error:
LSF libraries/headers not found;
add --with-lsf-inc and --with-lsf-lib with appropriate locations.

configure works in LSF 10.1.0.4.

**Comment by liuboxa** [comment]
Fixed. Please try the latest code.

The reason is _gcc -ansi_ can not recognize // comment.
