### ISSUE TITLE
missing function body for `drmaa_get_num_attr_values` ?

### ISSUE THREAD

**Issue by indraniel** [IBMSpectrumComputing/lsf-drmaa#6]
I see a function prototype for [`drmaa_get_num_attr_values`](https://github.com/PlatformLSF/lsf-drmaa/blob/master/drmaa_utils/drmaa_utils/drmaa.h#L316) inside `drmaa_utils/drmaa_utils/drmaa.h`, but no corresponding function body in any `*.c` files.  Is there supposed to be a function body?

**Comment by adamsla** [comment]
I just performed a code review.  Look at drmaa_utils/drmaa_utils/drmaa_base.c line 271.  The function is declared as an iterative.  Honestly, I've never seen this done before.
