### ISSUE TITLE
Build requires README

### ISSUE THREAD

**Issue by jakirkham** [IBMSpectrumComputing/lsf-drmaa#9]
Appears that the build expects to find the `README` file in a few cases, but not `README.md`, which is what it is now called. As a result, the build fails near the end. Would be good if the build was updated to handle `README.md` correctly.

Not to mention some of the associated build code expects the README is in reStructuredText when it is in Markdown. So this could use a refresh.

**Comment by liuboxa** [comment]
Hi there,
Thanks.  The code is updated.
